version: '3'
services:
  backend:
    build:
      context: https://github.com/FasterDelivery/BackEnd
    ports:
      - 3001:3001
  frontend:
    build:
      context: ./front
    ports:
      - 3000:3000